name: Template
version: '${project.version}'
main: com.claudiobo.template.Main
authors: [ Kledioz ]
api-version: 1.13 #1.13, 1.14, 1.15, 1.16, 1.17, 1.18 and 1.19 are the available versions.
commands:
  template: